services:

    backend:
        build: ./backend
        environment:
            HTTP_PORT: ":3001"
            DOMAIN_URI: "http://127.0.0.1"
        deploy:
            restart_policy:
                condition: on-failure
                delay: 2s
                window: 60s
        ports:
            - "3001:3001"
        networks:
            - internal

    frontend:
        build: ./frontend
        environment:
            VITE_API_URL: "http://127.0.0.1:3001"
        deploy:
            restart_policy:
                condition: on-failure
                delay: 2s
                window: 60s
        ports:
            - "3000:3000"
        networks:
            - internal

networks:
    internal:
