services:
    nginx:
        image: nginx:1.25-alpine
        depends_on:
            - frontend
            - backend
        volumes:
            - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
            - "${NGINX_PORT:-81}:80"
        networks:
            - internal

    backend:
        build: ./backend
        environment:
            HTTP_PORT: ":3001"
            DOMAIN_URI: "/api"
        deploy:
            restart_policy:
                condition: on-failure
                delay: 2s
                window: 60s
        networks:
            - internal

    frontend:
        build:
            context: ./frontend
            args:
                VITE_API_URL: "/api"
        deploy:
            restart_policy:
                condition: on-failure
                delay: 2s
                window: 60s
        networks:
            - internal

networks:
    internal:
